# Generated by Django 3.1.4 on 2020-12-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='v1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
