# Generated by Django 3.1.4 on 2020-12-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_user_v1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='v1',
        ),
    ]
