# Generated by Django 3.1.4 on 2021-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
