# Generated by Django 3.1.4 on 2021-01-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
